# 是否开启签名列表
signlist: true
# 使用远程
remote: true
# 并发限制
concurrent_limit: 10
# 远程地址
remoteurls:
  - name: 'Gitlab'
    url: 'https://gitlab.com/v17360963/starlight-qsign/raw/api/signlist.json'
  - name: 'Github'
    url: 'https://raw.githubusercontent.com/wuliya336/starlight-qsign/api/signlist.json'
  - name: 'Github Proxy'
    url: 'https://ghp.ci/https://raw.githubusercontent.com/wuliya336/starlight-qsign/api/signlist.json'