name: 格式化代码

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 使用 Prettier 格式化代码
        uses: creyD/prettier_action@v3.1
        with:
          prettier_version: "latest"    
          prettier_options: "--write ."  

      - name: 检查变更并提交
        run: |
          git diff --exit-code || (
            git config --global user.name "github-actions[bot]" &&
            git config --global user.email "github-actions[bot]@users.noreply.github.com" &&
            git add . &&
            git commit -m "✨ GitHub Actions: 格式化代码" &&
            git push
          )

      - name: 设置状态检查
        id: status_check
        run: |
          echo "status=success" >> $GITHUB_ENV
