name: 格式化代码

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: write 

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 使用 Prettier 格式化代码
        uses: creyD/prettier_action@v4.3
        with:
          prettier_version: "latest"      
          prettier_options: "--write ."    
          commit_message: "✨ GitHub Action: 格式化代码" 